
---
- name: Install lemp on Ubuntu
  hosts: all
  become: yes


  roles:
   - { role: nginx, when: ansible_system == 'Linux' }
   - { role: mysql, when: ansible_system == 'Linux' }
   - { role: php, when: ansible_system == 'Linux' }
